import { Inter } from "next/font/google";
import "./globals.css";
import DataProvider from "./global/DataProvider";
import Head from "next/head";
import SocketProvider from "./userdashboard/global/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BCS preparation online platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta name="google-site-verification" content="t89zb6eKmBGOYEtHSc2C1Kgh8mAeEHvp3gWrhUz7mA8" />
      </Head>
      <body className={inter.className}>
         <DataProvider>
           <SocketProvider>
              <div className="max-w-[1440px] mx-auto">{children}</div>
           </SocketProvider>
         </DataProvider>
        </body>
    </html>
  );
}
